# Generated by Django 3.0.4 on 2020-03-13 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField()),
                ('holds', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
