# Generated by Django 3.0.4 on 2020-03-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='id',
            new_name='uuid',
        ),
    ]
